export const initialAlerts = [
  {
    id: 1,
    name: "CPU Usage Spike",
    service: "Web Server",
    status: "High",
    triggeredAt: "08/09/2023 10:10:00",
    resolved: false,
  },
  {
    id: 2,
    name: "Disk Space Low",
    service: "Database",
    status: "Medium",
    triggeredAt: "07/09/2023 15:25:00",
    resolved: true,
  },
  {
    id: 3,
    name: "Memory Leak Detected",
    service: "API Service",
    status: "High",
    triggeredAt: "08/09/2023 08:20:00",
    resolved: false,
  },
  {
    id: 4,
    name: "Network Latency Spike",
    service: "Web Server",
    status: "Medium",
    triggeredAt: "07/09/2023 18:40:00",
    resolved: false,
  },
  {
    id: 5,
    name: "SSL Certificate Expiring",
    service: "Web Server",
    status: "Low",
    triggeredAt: "06/09/2023 14:05:00",
    resolved: true,
  },
  {
    id: 6,
    name: "Database Connection Timeout",
    service: "Database",
    status: "High",
    triggeredAt: "08/09/2023 09:45:00",
    resolved: false,
  },
  {
    id: 7,
    name: "Unauthorized Access Attempt",
    service: "Authentication Service",
    status: "Critical",
    triggeredAt: "08/09/2023 11:15:00",
    resolved: false,
  },
  {
    id: 8,
    name: "API Rate Limit Exceeded",
    service: "API Service",
    status: "Medium",
    triggeredAt: "08/09/2023 12:30:00",
    resolved: false,
  },
  {
    id: 9,
    name: "Service Downtime Detected",
    service: "Web Server",
    status: "Critical",
    triggeredAt: "08/09/2023 09:00:00",
    resolved: true,
  },
  {
    id: 10,
    name: "Backup Failed",
    service: "Database",
    status: "High",
    triggeredAt: "07/09/2023 20:30:00",
    resolved: false,
  },
  {
    id: 11,
    name: "File Upload Errors",
    service: "File Service",
    status: "Medium",
    triggeredAt: "06/09/2023 16:45:00",
    resolved: true,
  },
  {
    id: 12,
    name: "High Memory Usage",
    service: "API Service",
    status: "High",
    triggeredAt: "08/09/2023 07:50:00",
    resolved: false,
  },
  {
    id: 13,
    name: "Brute Force Attack Detected",
    service: "Authentication Service",
    status: "Critical",
    triggeredAt: "08/09/2023 06:35:00",
    resolved: false,
  },
  {
    id: 14,
    name: "Slow Query Execution",
    service: "Database",
    status: "Low",
    triggeredAt: "07/09/2023 19:05:00",
    resolved: true,
  },
  {
    id: 15,
    name: "Service Health Check Failed",
    service: "Web Server",
    status: "Medium",
    triggeredAt: "08/09/2023 13:45:00",
    resolved: false,
  },
  {
    id: 16,
    name: "Cache Server Overload",
    service: "Cache Service",
    status: "High",
    triggeredAt: "08/09/2023 09:30:00",
    resolved: false,
  },
  {
    id: 17,
    name: "Excessive 404 Errors",
    service: "Web Server",
    status: "Low",
    triggeredAt: "07/09/2023 12:20:00",
    resolved: true,
  },
  {
    id: 18,
    name: "Email Queue Delay",
    service: "Email Service",
    status: "Medium",
    triggeredAt: "07/09/2023 13:50:00",
    resolved: false,
  },
  {
    id: 19,
    name: "DNS Resolution Failure",
    service: "DNS Service",
    status: "Critical",
    triggeredAt: "08/09/2023 14:30:00",
    resolved: false,
  },
  {
    id: 20,
    name: "Server Reboot Required",
    service: "Web Server",
    status: "Low",
    triggeredAt: "06/09/2023 17:10:00",
    resolved: true,
  },
  {
    id: 21,
    name: "High CPU Temperature",
    service: "Web Server",
    status: "High",
    triggeredAt: "08/09/2023 10:50:00",
    resolved: false,
  },
  {
    id: 22,
    name: "Service Restart Required",
    service: "API Service",
    status: "Medium",
    triggeredAt: "07/09/2023 16:10:00",
    resolved: true,
  },
  {
    id: 23,
    name: "Unexpected System Shutdown",
    service: "Database",
    status: "Critical",
    triggeredAt: "08/09/2023 11:40:00",
    resolved: false,
  },
  {
    id: 24,
    name: "API Response Time Slow",
    service: "API Service",
    status: "High",
    triggeredAt: "08/09/2023 14:00:00",
    resolved: false,
  },
  {
    id: 25,
    name: "Failed Login Attempts",
    service: "Authentication Service",
    status: "Medium",
    triggeredAt: "08/09/2023 09:20:00",
    resolved: false,
  },
  {
    id: 26,
    name: "Low Memory Availability",
    service: "Cache Service",
    status: "High",
    triggeredAt: "08/09/2023 12:15:00",
    resolved: false,
  },
  {
    id: 27,
    name: "High Error Rate Detected",
    service: "Web Server",
    status: "Critical",
    triggeredAt: "08/09/2023 10:35:00",
    resolved: false,
  },
  {
    id: 28,
    name: "SSL Handshake Failure",
    service: "Web Server",
    status: "Medium",
    triggeredAt: "07/09/2023 11:45:00",
    resolved: true,
  },
  {
    id: 29,
    name: "Database Query Timeout",
    service: "Database",
    status: "High",
    triggeredAt: "08/09/2023 13:25:00",
    resolved: false,
  },
  {
    id: 30,
    name: "Unauthorized API Call",
    service: "API Service",
    status: "Critical",
    triggeredAt: "08/09/2023 15:00:00",
    resolved: false,
  },
  {
    id: 31,
    name: "High Network Bandwidth Usage",
    service: "Web Server",
    status: "Medium",
    triggeredAt: "07/09/2023 17:55:00",
    resolved: false,
  },
  {
    id: 32,
    name: "Database Backup Delay",
    service: "Database",
    status: "Low",
    triggeredAt: "06/09/2023 18:20:00",
    resolved: true,
  },
  {
    id: 33,
    name: "Cache Miss Rate High",
    service: "Cache Service",
    status: "Medium",
    triggeredAt: "08/09/2023 12:00:00",
    resolved: false,
  },
  {
    id: 34,
    name: "DNS Query Latency",
    service: "DNS Service",
    status: "Low",
    triggeredAt: "07/09/2023 16:05:00",
    resolved: true,
  },
  {
    id: 35,
    name: "Email Delivery Failure",
    service: "Email Service",
    status: "High",
    triggeredAt: "08/09/2023 11:30:00",
    resolved: false,
  },
];
