export const initialCustomers = [
  {
    userId: "q9w8e7r6t5z",
    username: "JSmith",
    email: "jsmith@example.com",
    fullName: "John Smith",
    created: "9/7/20 12:26:47 PM",
    balance: "525.55",
    country: "",
  },
  {
    userId: "eds2fwr1t2z",
    username: "ChrisTom",
    email: "vivodo3565@epeva.com",
    fullName: "Chris Thomas",
    created: "9/16/20 12:07:30 PM",
    balance: "",
    country: "",
  },
  {
    userId: "d9s1f1r9t1z",
    username: "IvanMikha",
    email: "ivan@mail.ru",
    fullName: "Ivan Mikhailov Sergej",
    created: "11/2/15 9:45:17 PM",
    balance: "",
    country: "RU",
  },
  {
    userId: "a8s9d8f7g6h5",
    username: "JaneD",
    email: "janedoe123@example.com",
    fullName: "Jane Doe",
    created: "10/10/21 08:15:22 AM",
    balance: "100.75",
    country: "US",
  },
  {
    userId: "jkl4m5n6o7p8",
    username: "RandyB",
    email: "randy.barker@samplemail.com",
    fullName: "Randy Barker",
    created: "8/14/19 3:14:25 PM",
    balance: "310.40",
    country: "UK",
  },
  {
    userId: "xzv7y6c5b4n3",
    username: "OliviaW",
    email: "olivia.wilson@example.com",
    fullName: "Olivia Wilson",
    created: "12/5/22 9:00:11 AM",
    balance: "",
    country: "CA",
  },
  {
    userId: "m9n8b7v6c5x4",
    username: "LeoB",
    email: "leo.brown@webmail.com",
    fullName: "Leo Brown",
    created: "3/8/20 5:47:22 PM",
    balance: "50.00",
    country: "",
  },
  {
    userId: "q1w2e3r4t5y6",
    username: "AshleyM",
    email: "ashley.martin@mailplace.com",
    fullName: "Ashley Martin",
    created: "4/3/18 10:05:30 AM",
    balance: "245.89",
    country: "",
  },
  {
    userId: "z9x8c7v6b5n4",
    username: "MiaJ",
    email: "mia.jones@domain.com",
    fullName: "Mia Jones",
    created: "7/1/21 12:45:19 PM",
    balance: "",
    country: "AU",
  },
  {
    userId: "b7v6c5x4z3a2",
    username: "LiamT",
    email: "liam.taylor@internet.com",
    fullName: "Liam Taylor",
    created: "2/23/19 6:34:58 AM",
    balance: "780.00",
    country: "",
  },
  {
    userId: "u1i2o3p4l5k6",
    username: "SophiaL",
    email: "sophia.lambert@randommail.com",
    fullName: "Sophia Lambert",
    created: "1/20/20 8:10:30 PM",
    balance: "",
    country: "DE",
  },
  {
    userId: "r3t4y5u6i7o8",
    username: "TomH",
    email: "tom.harris@contact.com",
    fullName: "Tom Harris",
    created: "5/15/21 11:22:33 AM",
    balance: "600.55",
    country: "FR",
  },
  {
    userId: "p2o1i9u8y7t6",
    username: "EllaG",
    email: "ella.garcia@abc.net",
    fullName: "Ella Garcia",
    created: "6/12/19 9:17:44 PM",
    balance: "450.00",
    country: "",
  },
  {
    userId: "m1n2b3v4c5x6",
    username: "NathanS",
    email: "nathan.smith@digital.com",
    fullName: "Nathan Smith",
    created: "10/30/20 1:23:45 PM",
    balance: "",
    country: "IN",
  },
  {
    userId: "w3e4r5t6y7u8",
    username: "GraceF",
    email: "grace.foster@example.org",
    fullName: "Grace Foster",
    created: "3/14/21 7:58:31 AM",
    balance: "120.00",
    country: "ES",
  },
  {
    userId: "k5j4h3g2f1d9",
    username: "LucasW",
    email: "lucas.white@myemail.com",
    fullName: "Lucas White",
    created: "11/17/18 5:27:19 AM",
    balance: "300.00",
    country: "",
  },
  {
    userId: "z6x7c8v9b0n1",
    username: "ChloeK",
    email: "chloe.king@service.com",
    fullName: "Chloe King",
    created: "9/9/19 2:15:55 PM",
    balance: "90.25",
    country: "IT",
  },
  {
    userId: "s4d5f6g7h8j9",
    username: "EthanA",
    email: "ethan.adams@network.net",
    fullName: "Ethan Adams",
    created: "8/21/20 4:05:44 PM",
    balance: "",
    country: "",
  },
  {
    userId: "a7s8d9f0g1h2",
    username: "ZoeM",
    email: "zoe.miller@cloudmail.com",
    fullName: "Zoe Miller",
    created: "2/2/19 10:59:12 AM",
    balance: "230.00",
    country: "JP",
  },
  {
    userId: "q3w4e5r6t7y8",
    username: "HenryL",
    email: "henry.lewis@freemail.com",
    fullName: "Henry Lewis",
    created: "6/27/22 8:45:10 PM",
    balance: "",
    country: "",
  },
];

export const customerData = {
  q9w8e7r6t5z: {
    fullName: "John Smith",
    email: "jsmith@example.com",
    balance: 525.55,
    country: "US",
    created: "9/7/20",
    transactions: ["Transaction 1", "Transaction 2"],
  },
  eds2fwr1t2z: {
    fullName: "Chris Thomas",
    email: "vivodo3565@epeva.com",
    balance: 0,
    country: "US",
    created: "9/16/20",
    transactions: [],
  },
  d9s1f1r9t1z: {
    fullName: "Ivan Mikhailov Sergej",
    email: "ivan@mail.ru",
    balance: 0,
    country: "RU",
    created: "11/2/15",
    transactions: [],
  },
  a8s9d8f7g6h5: {
    fullName: "Jane Doe",
    email: "janedoe123@example.com",
    balance: 100.75,
    country: "US",
    created: "10/10/21",
    transactions: ["Transaction 1"],
  },
  jkl4m5n6o7p8: {
    fullName: "Randy Barker",
    email: "randy.barker@samplemail.com",
    balance: 310.4,
    country: "UK",
    created: "8/14/19",
    transactions: ["Transaction 1", "Transaction 2"],
  },
  xzv7y6c5b4n3: {
    fullName: "Olivia Wilson",
    email: "olivia.wilson@example.com",
    balance: 0,
    country: "CA",
    created: "12/5/22",
    transactions: [],
  },
  m9n8b7v6c5x4: {
    fullName: "Leo Brown",
    email: "leo.brown@webmail.com",
    balance: 50.0,
    country: "",
    created: "3/8/20",
    transactions: ["Transaction 1"],
  },
  q1w2e3r4t5y6: {
    fullName: "Ashley Martin",
    email: "ashley.martin@mailplace.com",
    balance: 245.89,
    country: "",
    created: "4/3/18",
    transactions: [],
  },
  z9x8c7v6b5n4: {
    fullName: "Mia Jones",
    email: "mia.jones@domain.com",
    balance: 0,
    country: "AU",
    created: "7/1/21",
    transactions: ["Transaction 1", "Transaction 2"],
  },
  b7v6c5x4z3a2: {
    fullName: "Liam Taylor",
    email: "liam.taylor@internet.com",
    balance: 780.0,
    country: "",
    created: "2/23/19",
    transactions: [],
  },
  u1i2o3p4l5k6: {
    fullName: "Sophia Lambert",
    email: "sophia.lambert@randommail.com",
    balance: 0,
    country: "DE",
    created: "1/20/20",
    transactions: [],
  },
  r3t4y5u6i7o8: {
    fullName: "Tom Harris",
    email: "tom.harris@contact.com",
    balance: 600.55,
    country: "FR",
    created: "5/15/21",
    transactions: ["Transaction 1"],
  },
  p2o1i9u8y7t6: {
    fullName: "Ella Garcia",
    email: "ella.garcia@abc.net",
    balance: 450.0,
    country: "",
    created: "6/12/19",
    transactions: [],
  },
  m1n2b3v4c5x6: {
    fullName: "Nathan Smith",
    email: "nathan.smith@digital.com",
    balance: 0,
    country: "IN",
    created: "10/30/20",
    transactions: [],
  },
  w3e4r5t6y7u8: {
    fullName: "Grace Foster",
    email: "grace.foster@example.org",
    balance: 120.0,
    country: "ES",
    created: "3/14/21",
    transactions: ["Transaction 1", "Transaction 2"],
  },
  k5j4h3g2f1d9: {
    fullName: "Lucas White",
    email: "lucas.white@myemail.com",
    balance: 300.0,
    country: "",
    created: "11/17/18",
    transactions: [],
  },
  z6x7c8v9b0n1: {
    fullName: "Chloe King",
    email: "chloe.king@service.com",
    balance: 90.25,
    country: "IT",
    created: "9/9/19",
    transactions: [],
  },
  s4d5f6g7h8j9: {
    fullName: "Ethan Adams",
    email: "ethan.adams@network.net",
    balance: 0,
    country: "",
    created: "8/21/20",
    transactions: ["Transaction 1"],
  },
  a7s8d9f0g1h2: {
    fullName: "Zoe Miller",
    email: "zoe.miller@cloudmail.com",
    balance: 230.0,
    country: "JP",
    created: "2/2/19",
    transactions: [],
  },
  q3w4e5r6t7y8: {
    fullName: "Henry Lewis",
    email: "henry.lewis@freemail.com",
    balance: 0,
    country: "",
    created: "6/27/22",
    transactions: ["Transaction 1", "Transaction 2"],
  },
};
