export const initialIncidents = [
  {
    id: 1,
    status: "In progress",
    assignedTo: "John Doe",
    details: "Issue 1",
    severity: "Critical",
    date: "2023-04-15",
  },
  {
    id: 2,
    status: "New",
    assignedTo: "Sarah Adams",
    details: "Issue 2",
    severity: "High",
    date: "2023-05-01",
  },
  {
    id: 3,
    status: "In progress",
    assignedTo: "Lisa Martinez",
    details: "Issue 3",
    severity: "High",
    date: "2023-06-10",
  },
  {
    id: 4,
    status: "New",
    assignedTo: "Michael Rodriguez",
    details: "Issue 4",
    severity: "Medium",
    date: "2023-07-01",
  },
  {
    id: 5,
    status: "In progress",
    assignedTo: "Steve Smith",
    details: "Issue 5",
    severity: "Critical",
    date: "2023-08-21",
  },
  {
    id: 6,
    status: "New",
    assignedTo: "Anna Brown",
    details: "Issue 6",
    severity: "Low",
    date: "2023-09-01",
  },
  {
    id: 7,
    status: "In progress",
    assignedTo: "Emily Johnson",
    details: "Issue 7",
    severity: "Medium",
    date: "2023-04-18",
  },
  {
    id: 8,
    status: "New",
    assignedTo: "Robert King",
    details: "Issue 8",
    severity: "High",
    date: "2023-05-05",
  },
  {
    id: 9,
    status: "In progress",
    assignedTo: "Olivia Thompson",
    details: "Issue 9",
    severity: "Critical",
    date: "2023-05-20",
  },
  {
    id: 10,
    status: "New",
    assignedTo: "William Garcia",
    details: "Issue 10",
    severity: "Low",
    date: "2023-06-05",
  },
  {
    id: 11,
    status: "In progress",
    assignedTo: "Sophia Wilson",
    details: "Issue 11",
    severity: "High",
    date: "2023-06-22",
  },
  {
    id: 12,
    status: "New",
    assignedTo: "Daniel Lewis",
    details: "Issue 12",
    severity: "Critical",
    date: "2023-07-12",
  },
  {
    id: 13,
    status: "In progress",
    assignedTo: "Isabella Clark",
    details: "Issue 13",
    severity: "Medium",
    date: "2023-07-15",
  },
  {
    id: 14,
    status: "New",
    assignedTo: "James Young",
    details: "Issue 14",
    severity: "High",
    date: "2023-08-01",
  },
  {
    id: 15,
    status: "In progress",
    assignedTo: "Evelyn Wright",
    details: "Issue 15",
    severity: "Low",
    date: "2023-08-14",
  },
  {
    id: 16,
    status: "New",
    assignedTo: "Christopher Hall",
    details: "Issue 16",
    severity: "Critical",
    date: "2023-08-20",
  },
  {
    id: 17,
    status: "In progress",
    assignedTo: "Charlotte Turner",
    details: "Issue 17",
    severity: "Medium",
    date: "2023-08-30",
  },
  {
    id: 18,
    status: "New",
    assignedTo: "Benjamin Allen",
    details: "Issue 18",
    severity: "High",
    date: "2023-09-01",
  },
  {
    id: 19,
    status: "In progress",
    assignedTo: "Abigail Scott",
    details: "Issue 19",
    severity: "Critical",
    date: "2023-09-05",
  },
  {
    id: 20,
    status: "New",
    assignedTo: "David Phillips",
    details: "Issue 20",
    severity: "Medium",
    date: "2023-09-10",
  },
  {
    id: 21,
    status: "In progress",
    assignedTo: "Mia Edwards",
    details: "Issue 21",
    severity: "Low",
    date: "2023-09-12",
  },
  {
    id: 22,
    status: "New",
    assignedTo: "Chloe Anderson",
    details: "Issue 22",
    severity: "High",
    date: "2023-09-14",
  },
  {
    id: 23,
    status: "In progress",
    assignedTo: "Liam Taylor",
    details: "Issue 23",
    severity: "Critical",
    date: "2023-09-15",
  },
  {
    id: 24,
    status: "New",
    assignedTo: "Zoe Moore",
    details: "Issue 24",
    severity: "Low",
    date: "2023-09-17",
  },
  {
    id: 25,
    status: "In progress",
    assignedTo: "Henry Walker",
    details: "Issue 25",
    severity: "Medium",
    date: "2023-09-18",
  },
  {
    id: 26,
    status: "New",
    assignedTo: "Ella Harris",
    details: "Issue 26",
    severity: "Critical",
    date: "2023-09-20",
  },
  {
    id: 27,
    status: "In progress",
    assignedTo: "Aiden Lewis",
    details: "Issue 27",
    severity: "High",
    date: "2023-09-22",
  },
  {
    id: 28,
    status: "New",
    assignedTo: "Grace Robinson",
    details: "Issue 28",
    severity: "Medium",
    date: "2023-09-24",
  },
  {
    id: 29,
    status: "In progress",
    assignedTo: "Mason White",
    details: "Issue 29",
    severity: "Low",
    date: "2023-09-25",
  },
  {
    id: 30,
    status: "New",
    assignedTo: "Harper Davis",
    details: "Issue 30",
    severity: "High",
    date: "2023-09-26",
  },
  {
    id: 31,
    status: "In progress",
    assignedTo: "Lucas Thompson",
    details: "Issue 31",
    severity: "Critical",
    date: "2023-09-28",
  },
  {
    id: 32,
    status: "New",
    assignedTo: "Aria Martinez",
    details: "Issue 32",
    severity: "Low",
    date: "2023-09-29",
  },
  {
    id: 33,
    status: "In progress",
    assignedTo: "Ethan Clark",
    details: "Issue 33",
    severity: "Medium",
    date: "2023-10-01",
  },
  {
    id: 34,
    status: "New",
    assignedTo: "Victoria Allen",
    details: "Issue 34",
    severity: "High",
    date: "2023-10-03",
  },
  {
    id: 35,
    status: "In progress",
    assignedTo: "Dylan Young",
    details: "Issue 35",
    severity: "Critical",
    date: "2023-10-05",
  },
  {
    id: 36,
    status: "New",
    assignedTo: "Madison Scott",
    details: "Issue 36",
    severity: "Medium",
    date: "2023-10-06",
  },
];
